#!/bin/zsh

senha="juangomes1519"


echo ""
echo -e  " --- configurando o externo a direita do interno ---"
echo ${senha} | ( xrandr --output eDP-1 --auto --below HDMI-1 )
echo ""

echo ""
echo -e  " --- alterando o brilho da tela interna para 100%---"
echo ${senha} | ( xrandr --output eDP-1 --brightness 0.8 )
echo ""


