#!/bin/bash

senha="juangomes1519"


echo ""
echo -e  " --- atualizando todos os pacotes instalados --- "
echo ${senha} | ( sudo -S apt-get -y update )
echo ""

echo ""
echo -e  " --- instalando todas as atualizoes fora do flatpak --- "
echo ${senha} | ( sudo -S apt-get -y full-upgrade )
echo ""

echo ""
echo -e  " --- instalando todas as atualizoes do flatpak ---"
echo ${senha} | ( flatpak -y update )
echo ""


